name: Validate
on:
  - push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rinchsan/renovate-config-validator@v0.0.5
        with:
          pattern: "!(package|package-lock).json"
